services:
  postgres:
    image: supabase/postgres:17.6.1.067
    platform: linux/amd64
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: America/Chicago
      PGTZ: America/Chicago
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./data/mlflow:/mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --serve-artifacts --artifacts-destination /mlflow/artifacts
    restart: unless-stopped
