from langchain_core.tools import BaseTool

from app.clients.brief import (
    compose_campaign_brief,
    delete_campaign_brief,
    describe_brief_schema,
    find_campaign_brief,
    generate_campaign_brief,
    get_brief_types,
    get_campaign_brief,
    save_campaign_brief,
    update_campaign_brief,
)
from app.clients.brand_kit import (
    create_org_brand_kit,
    get_brand_voice_summary,
    import_brand_document,
    list_org_brand_kits,
    review_content_against_brand,
)
from app.clients.content_workflow import (
    get_phase_artifact_content,
    save_phase_artifact,
    scan_content_project_status,
)
from app.clients.marketing_research import search_market_research
from app.clients.sites import (
    add_language_to_site,
    create_marketing_site,
    create_site_collection,
    delete_marketing_site,
    set_fallback_language,
    get_environment_languages,
    get_site_context,
    get_site_templates,
    list_all_sites,
    list_site_collections,
    list_site_languages,
    remove_language_from_site,
    validate_site_name,
)
from app.clients.pages_api import (
    add_component_on_page,
    add_language_to_page,
    create_page,
    create_page_version,
    create_site_pages,
    delete_page,
    duplicate_page,
    find_pages,
    get_all_pages_by_site,
    get_allowed_components_by_placeholder,
    get_components_on_page,
    get_insert_options,
    get_page_preview_url,
    get_page_state,
    navigate_to_page,
    open_page,
    rename_page,
    search_pages,
    set_component_datasource,
    update_page_fields,
)
from app.clients.image_search import (
    index_media_library_images,
    search_site_images,
)
from app.clients.publishing_api import (
    get_publishing_job,
    get_publishing_summary,
    list_publishing_jobs,
    publish_content,
)
from app.clients.flows_api import (
    get_flow_definition,
    get_flow_variant,
    list_page_flows,
    setup_flow_variant,
)
from app.clients.personalization_api import (
    create_component_ab_test,
    create_perso_version,
    create_perso_version_multi,
    get_condition_template_by_id,
    get_condition_templates,
    get_personalization_versions,
    update_ab_test,
    update_perso_version,
)
from app.clients.assets_api import (
    get_asset_info,
    search_assets,
    update_asset,
    upload_asset,
)
from app.clients.components_api import (
    create_component_ds,
    get_component,
    list_components,
    search_component_datasources,
)
from app.clients.content_api import (
    create_content_item,
    delete_content,
    get_content_item,
    list_content_insert_options,
    update_content,
    update_fields_on_item,
)
from app.clients.ui_tools import present_options

_mcp_tools: list[BaseTool] = []


def set_mcp_tools(tools: list[BaseTool]) -> None:
    global _mcp_tools
    _mcp_tools = tools


def get_all_tools() -> list[BaseTool]:
    return [
        *_mcp_tools,
        scan_content_project_status,
        save_phase_artifact,
        get_phase_artifact_content,
        get_site_context,
        list_all_sites,
        list_site_collections,
        create_site_collection,
        get_site_templates,
        get_environment_languages,
        validate_site_name,
        create_marketing_site,
        delete_marketing_site,
        list_site_languages,
        add_language_to_site,
        set_fallback_language,
        remove_language_from_site,
        search_market_research,
        list_org_brand_kits,
        get_brand_voice_summary,
        create_org_brand_kit,
        import_brand_document,
        review_content_against_brand,
        search_pages,
        find_pages,
        open_page,
        navigate_to_page,
        get_insert_options,
        create_page,
        create_site_pages,
        get_page_state,
        rename_page,
        duplicate_page,
        update_page_fields,
        create_page_version,
        delete_page,
        add_language_to_page,
        get_components_on_page,
        add_component_on_page,
        set_component_datasource,
        get_allowed_components_by_placeholder,
        get_page_preview_url,
        get_all_pages_by_site,
        search_site_images,
        index_media_library_images,
        publish_content,
        get_publishing_job,
        list_publishing_jobs,
        get_publishing_summary,
        get_brief_types,
        describe_brief_schema,
        generate_campaign_brief,
        save_campaign_brief,
        compose_campaign_brief,
        get_campaign_brief,
        update_campaign_brief,
        find_campaign_brief,
        delete_campaign_brief,
        list_page_flows,
        get_flow_definition,
        get_flow_variant,
        setup_flow_variant,
        get_personalization_versions,
        get_condition_templates,
        get_condition_template_by_id,
        create_perso_version,
        create_perso_version_multi,
        update_perso_version,
        create_component_ab_test,
        update_ab_test,
        search_assets,
        get_asset_info,
        upload_asset,
        update_asset,
        list_components,
        get_component,
        create_component_ds,
        search_component_datasources,
        create_content_item,
        get_content_item,
        update_content,
        update_fields_on_item,
        delete_content,
        list_content_insert_options,
        present_options,
    ]
